services:
  server:
    image: z21_11_server
    networks:
      - z21_network
    build: ./server
    container_name: z21_11_server
    expose:
      - ${SERVER_PORT}
    command: python -u ./server.py ${SERVER_PORT}
  client:
    image: z21_11_client
    depends_on:
      - server
    networks:
      - z21_network
    build: ./client
    container_name: z21_11_client
    command: ./client 172.21.21.2 ${SERVER_PORT} ${PACKETS_NUM} ${SLEEP_TIME}

networks:
  z21_network:
    external: true
